apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: Service
metadata:
  name: webirfan
  namespace: production
  labels:
    app: webirfan
spec:
  selector:
    app: webirfan
  ports:
  - port: 80
    name: http
    targerPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webirfan
  namespace: production
spec:
  selector:
    matchLabels:
      app: webirfan
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: webirfan
      spec:
        container:
        - name: webirfan
          image: asia.gcr.io/$PROJECT_ID/production/webirfan:$SHORT_SHA
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: webirfan
          resources:
            requests:
              cpu: 50m